version: '3.7'

services:
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - node.name=single-node
      - cluster.name=backtony
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - docker-bridge

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - docker-bridge

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: paratrip
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    networks:
      - docker-bridge

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - docker-bridge

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/paratrip?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_ELASTICSEARCH_URIS: http://es:9200
      REDIS_HOST: redis
    depends_on:
      - es
      - kibana
      - mysql
      - redis
    ports:
      - 8080:8080
    container_name: paratrip
    networks:
      - docker-bridge

networks:
  docker-bridge:
    driver: bridge
