name: paratrip CI/CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # YML 파일 생성
      - name: Set YML
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find application/src

      - name: Set YML PRODUCTION
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_PRODUCTION_YML }}" | base64 --decode > src/main/resources/application-production.yml
          find application/src

      # Gradle Build
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      # Time Setting
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
        shell: bash

      # Docker Config
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: build and release to DockerHub
        env:
          NAME: ${{secrets.DOCKER_USERNAME}}
          REPO: paratrip
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted ]
    steps:
      - name: Stop and Remove Docker Image
        run: |
          sudo docker ps -q --filter "name=paratrip" | grep -q . && sudo docker stop "paratrip" && sudo docker rmi -f "${{secrets.DOCKER_USERNAME}}/paratrip"
          sudo docker pull ${{secrets.DOCKER_USERNAME}}/paratrip
      - name: Docker run
        run: |
          sudo docker run -d --name paratrip --rm -p 8080:8080 ${{secrets.DOCKER_USERNAME}}/paratrip